/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ConversasIndexRouteImport } from './routes/conversas.index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as ConversasIdRouteImport } from './routes/conversas.$id'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as B2bSignupRouteImport } from './routes/b2b/signup'
import { Route as B2bLoginRouteImport } from './routes/b2b/login'
import { Route as B2bDashboardRouteImport } from './routes/b2b/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIndexRoute = ConversasIndexRouteImport.update({
  id: '/conversas/',
  path: '/conversas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIdRoute = ConversasIdRouteImport.update({
  id: '/conversas/$id',
  path: '/conversas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bSignupRoute = B2bSignupRouteImport.update({
  id: '/b2b/signup',
  path: '/b2b/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bLoginRoute = B2bLoginRouteImport.update({
  id: '/b2b/login',
  path: '/b2b/login',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bDashboardRoute = B2bDashboardRouteImport.update({
  id: '/b2b/dashboard',
  path: '/b2b/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/b2b/dashboard': typeof B2bDashboardRoute
  '/b2b/login': typeof B2bLoginRoute
  '/b2b/signup': typeof B2bSignupRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/conversas/': typeof ConversasIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/b2b/dashboard': typeof B2bDashboardRoute
  '/b2b/login': typeof B2bLoginRoute
  '/b2b/signup': typeof B2bSignupRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/communities': typeof CommunitiesIndexRoute
  '/conversas': typeof ConversasIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/b2b/dashboard': typeof B2bDashboardRoute
  '/b2b/login': typeof B2bLoginRoute
  '/b2b/signup': typeof B2bSignupRoute
  '/communities/$id': typeof CommunitiesIdRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/conversas/': typeof ConversasIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/feed'
    | '/groups'
    | '/login'
    | '/metricas'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/b2b/dashboard'
    | '/b2b/login'
    | '/b2b/signup'
    | '/communities/$id'
    | '/conversas/$id'
    | '/messages/$id'
    | '/communities/'
    | '/conversas/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/feed'
    | '/groups'
    | '/login'
    | '/metricas'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/b2b/dashboard'
    | '/b2b/login'
    | '/b2b/signup'
    | '/communities/$id'
    | '/conversas/$id'
    | '/messages/$id'
    | '/communities'
    | '/conversas'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/feed'
    | '/groups'
    | '/login'
    | '/metricas'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/b2b/dashboard'
    | '/b2b/login'
    | '/b2b/signup'
    | '/communities/$id'
    | '/conversas/$id'
    | '/messages/$id'
    | '/communities/'
    | '/conversas/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FeedRoute: typeof FeedRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  MetricasRoute: typeof MetricasRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  B2bDashboardRoute: typeof B2bDashboardRoute
  B2bLoginRoute: typeof B2bLoginRoute
  B2bSignupRoute: typeof B2bSignupRoute
  CommunitiesIdRoute: typeof CommunitiesIdRoute
  ConversasIdRoute: typeof ConversasIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  ConversasIndexRoute: typeof ConversasIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/': {
      id: '/conversas/'
      path: '/conversas'
      fullPath: '/conversas/'
      preLoaderRoute: typeof ConversasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/$id': {
      id: '/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof ConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/signup': {
      id: '/b2b/signup'
      path: '/b2b/signup'
      fullPath: '/b2b/signup'
      preLoaderRoute: typeof B2bSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/login': {
      id: '/b2b/login'
      path: '/b2b/login'
      fullPath: '/b2b/login'
      preLoaderRoute: typeof B2bLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/dashboard': {
      id: '/b2b/dashboard'
      path: '/b2b/dashboard'
      fullPath: '/b2b/dashboard'
      preLoaderRoute: typeof B2bDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FeedRoute: FeedRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  MetricasRoute: MetricasRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  B2bDashboardRoute: B2bDashboardRoute,
  B2bLoginRoute: B2bLoginRoute,
  B2bSignupRoute: B2bSignupRoute,
  CommunitiesIdRoute: CommunitiesIdRoute,
  ConversasIdRoute: ConversasIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  ConversasIndexRoute: ConversasIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
